# Generated by Django 5.0.7 on 2024-08-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representatives.position')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representatives.ward')),
            ],
        ),
    ]
