# Generated by Django 5.0.7 on 2024-08-05 11:25

from django.db import migrations, models
import django.db.models.deletion

def create_default_county(apps, schema_editor):
    County = apps.get_model('representatives', 'County')
    County.objects.create(name='Default County')

class Migration(migrations.Migration):

    dependencies = [
        ('representatives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(create_default_county),
        migrations.AddField(
            model_name='ward',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='representatives.county', null=True),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('representatives', 'Ward').objects.update(
                county=apps.get_model('representatives', 'County').objects.first()
            )
        ),
        migrations.AlterField(
            model_name='ward',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='representatives.county'),
        ),
    ]